name: Generate and submit dependency graph for nextflow
on:
    pull_request:

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Generate and submit dependency graph for nextflow
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-resolution-task: ":nextflow:dependencies"
        additional-arguments: "--configuration runtimeClasspath"
        dependency-graph: generate-and-submit
